### ISSUE TITLE
Issue with status

### ISSUE THREAD

**Issue by TEJAlions** [EtricKombat/KOBman#11]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Please tick one according to the issue you are facing with:
- [ ] Issue facing with installation or setup.
- [ ] Issue facing while running a environment.
- [ ] Issue facing while adding a new environment or new file.
- [x] Other issues: please provide the issue in the comment box

Please explain the Issue / Feature Request here:
Please provide the necessary screenshots or documents regarding the issue:

**Comment by TEJAlions** [comment]
![Uploading Screenshot from 2020-02-03 14-14-52.png…]()

**Comment by TEJAlions** [comment]
![Screenshot from 2020-02-03 14-14-52](https://user-images.githubusercontent.com/35185173/73638471-7a575480-4690-11ea-80c1-a39fa4114d20.png)
it showing the list of directory including all the files.please check

**Comment by EtricKombat-zz** [comment]
Unable to re-produce this issue , hence closing this. Feel free to re-open and report back to us if facing this issue again
