### ISSUE TITLE
Error_Install_KOBman_ENVIRONMENT

### ISSUE THREAD

**Issue by Teenasusanvarghese** [EtricKombat/KOBman#110]
kob install --env KOBman --version 0.0.1

kob install --environment KOBman --version 0.0.1

![image](https://user-images.githubusercontent.com/54981984/89255780-22e67100-d640-11ea-9b06-6b1e78313aeb.png)

kob install --environment KOBman  (default version )

![image](https://user-images.githubusercontent.com/54981984/89256252-51188080-d641-11ea-848e-5cca2fa43504.png)

Error after exporting the Github id 

![image](https://user-images.githubusercontent.com/54981984/89256170-21697880-d641-11ea-987d-9b203fdc700f.png)

**Comment by EtricKombat-zz** [comment]
@asa1997 can you review this issue  ?

**Comment by asa1997** [comment]
@Teenasusanvarghese @EtricKombat  Please do a cleanup 
  - rm -rf $HOME/KOBman_env
  - rm -rf $HOME/.kobman

Please run the above two steps to do the cleanup and then install utility and try again

**Comment by Teenasusanvarghese** [comment]
@EtricKombat @asa1997 

Install Command has been tested out successfully. Please refer below

![image](https://user-images.githubusercontent.com/54981984/89262088-c63d8300-d64c-11ea-87b8-71ad2eddfc3c.png)

**Comment by Teenasusanvarghese** [comment]
Install Command has been tested out successfully. Please refer above
