### ISSUE TITLE
tree ~/.kobman/envs/kob_env_*/current 

### ISSUE THREAD

**Issue by Teenasusanvarghese** [EtricKombat/KOBman#114]
-[cat value of current file in each envi ~/.kobman/envs/kob_env_*/current ] 

No such file found like kob_env,please refer below

![image](https://user-images.githubusercontent.com/54981984/89270504-0e62a280-d659-11ea-8947-339a1792491c.png)

![image](https://user-images.githubusercontent.com/54981984/89270592-2cc89e00-d659-11ea-9b19-264be497a532.png)

[tree command should be displayed on ~/Dev_KOBman]

![image](https://user-images.githubusercontent.com/54981984/89270701-5da8d300-d659-11ea-8528-c1c85e737852.png)

**Comment by EtricKombat-zz** [comment]
@Teenasusanvarghese , mistake from our end...need to update that step...and get back to you
