### ISSUE TITLE
avoid "GnuTLS recv error (-110): The TLS connection was non-properly terminated"

### ISSUE THREAD

**Issue by EtricKombat-zz** [EtricKombat/KOBman#166]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [x] Issue facing with installation or setup of KOBman utility. 
- [ ] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [ ] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

avoid "GnuTLS recv error (-110): The TLS connection was non-properly terminated"
____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/92697020-5cf61180-f368-11ea-8958-4311d0ac9d03.png)

**Comment by EtricKombat-zz** [comment]
# Suggested solution : 

https://github.com/curl/curl/pull/3148

**Comment by yzashish** [comment]
Auto corrected after connecting pulse and updating system

**Comment by EtricKombat-zz** [comment]
vpn issue
