### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by EtricKombat-zz** [EtricKombat/KOBman#167]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [x] Issue facing with installation or setup of KOBman utility. 
- [ ] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [ ] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

-getting "NET::ERR_CERT_AUTHORITY_INVALID " while trying to connect up browser from ubuntu 
- tried with firefox,chromium...etc
____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/92698578-33d68080-f36a-11ea-86c3-b20d16437cde.png)

![image](https://user-images.githubusercontent.com/33585301/92698628-418c0600-f36a-11ea-9daf-704d58ac2c31.png)

**Comment by yzashish** [comment]
Automatically resolved after connecting with pulse

**Comment by EtricKombat-zz** [comment]
## Suggestion

Enabling VPN fixed this once.
